[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "staging" }

[headers]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
